// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __philentropy_h__
#define __philentropy_h__

#include "philentropy_RcppExports.h"

#endif // __philentropy_h__
