#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/*
The following symbols/expressions for .NAME have been omitted

_philentropy_pearson_corr_centred
_philentropy_pearson_corr_uncentred
_philentropy_squared_pearson_corr
_philentropy_DistMatrixWithoutUnitDF
_philentropy_DistMatrixMinkowskiMAT
_philentropy_DistMatrixWithoutUnitMAT
_philentropy_DistMatrixWithUnitDF
_philentropy_DistMatrixWithUnitMAT
_philentropy_custom_log2
_philentropy_custom_log10
_philentropy_euclidean
_philentropy_manhattan
_philentropy_minkowski
_philentropy_chebyshev
_philentropy_sorensen
_philentropy_gower
_philentropy_soergel
_philentropy_kulczynski_d
_philentropy_canberra
_philentropy_lorentzian
_philentropy_intersection_dist
_philentropy_wave_hedges
_philentropy_czekanowski
_philentropy_motyka
_philentropy_tanimoto
_philentropy_ruzicka
_philentropy_inner_product
_philentropy_harmonic_mean_dist
_philentropy_cosine_dist
_philentropy_kumar_hassebrook
_philentropy_jaccard
_philentropy_dice_dist
_philentropy_fidelity
_philentropy_bhattacharyya
_philentropy_hellinger
_philentropy_matusita
_philentropy_squared_chord
_philentropy_squared_euclidean
_philentropy_pearson_chi_sq
_philentropy_neyman_chi_sq
_philentropy_squared_chi_sq
_philentropy_prob_symm_chi_sq
_philentropy_divergence_sq
_philentropy_clark_sq
_philentropy_additive_symm_chi_sq
_philentropy_kullback_leibler_distance
_philentropy_jeffreys
_philentropy_k_divergence
_philentropy_topsoe
_philentropy_jensen_shannon
_philentropy_jensen_difference
_philentropy_taneja
_philentropy_kumar_johnson
_philentropy_avg
_philentropy_Ecpp
_philentropy_JEcpp
_philentropy_CEcpp
_philentropy_MIcpp
_philentropy_as_matrix
_philentropy_as_data_frame
_philentropy_sum_rcpp
_philentropy_est_prob_empirical

Most likely possible values need to be added below.
*/

/* FIXME: 
Check these declarations against the C/Fortran source code.
*/

/* .Call calls */
extern SEXP _philentropy_RcppExport_registerCCallable();

static const R_CallMethodDef CallEntries[] = {
  {"_philentropy_RcppExport_registerCCallable", (DL_FUNC) &_philentropy_RcppExport_registerCCallable, 0},
  {NULL, NULL, 0}
};

void R_init_philentropy(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
